name: ostorlab github action.
description: ostorlab github action.
inputs:
  plan:
    description: Specify which plan to use for scan.
    required: true
    default: free
  asset_type:
    description: Type of scan android|ios.
    required: true
  target:
    description: Path to file .apk|.ios file.
    required: true
  scan_title:
    description: Title for your scan.
    required: false
  ostorlab_api_key:
    description: Api key from ostorlab.
    required: true
  break_on_risk_rating:
    description: Api key from ostorlab.
    required: false
  max_wait_minutes:
    description: maximum mintes to wait for scan results.
    required: false
outputs:
  scan_id:
    description: id of the created scan.
  status:
    description: status of scan.
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "shield"
  color: "blue"
