on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
jobs:
  ostorlab_test:
    runs-on: ubuntu-latest
    name: Test ostorlab CI actions.
    steps:
      - uses: actions/checkout@v2
      - name: build ostorlab.apk
        run: mv tests/InsecureBankv2.apk ostorlab.apk
      - name: Launch Ostorlab scan
        id: start_scan
        uses: ./
        with:
          scan_profile: fast_scan # Specify which scan profile to use for the scan (check scan section).
          asset_type: android-apk # type of asset to scan.
          target: ostorlab.apk # path for target tto scan.
          scan_title: title_scan_ci # type a title for your scan.
          ostorlab_api_key: ${{ secrets.ostorlab_api_key }} # your secret api key.
      - name: Get scan id
        run: echo "Scan Created with id ${{ steps.start_scan.outputs.scan_id }} you can access the full report at https://report.ostorlab.co/scan/${{ steps.start_scan.outputs.scan_id }}/"
